server:
  port: 9100
  servlet:
    contextPath: /boot-nacos
  
spring:
  application:
    name: boot-nacos
    
nacos:
  config:
    server-addr: 192.168.43.104:8848
  discovery:
    server-addr: 192.168.43.104:8848

management:
  endpoints:
    web:
      exposure:
        include: health,info,nacos-discovery  